### ISSUE TITLE
an even simpler project?

### ISSUE THREAD

**Issue by nilsbecker** [mjambon/dune-starter#2]
how about a template for an application not intended for publication on opam? 

e.g. a few 'library' modules that are used in an 'application script' which is only intended for in-house use. would you still recommend to package that locally as an opam package?

**Comment by mjambon** [comment]
You certainly can use the `sample-application` template for that.
Are there specific things you'd like to simplify? I personally find that
renaming sample directories, editing their list in `jbuild`, and removing
sample files could be automated away but this would require an IDE or some
kind of tool.

**Comment by nilsbecker** [comment]
maybe the opam files could be left out? but i guess there is not so much room for simplification anyway...
